### ISSUE TITLE
Добавить поддержку хэша

### ISSUE THREAD

**Issue by kosheeta** [YerinAlexey/vkui-navigation#6]
В любом URL может быть хэш. Например:
```
https://vkma.host/vkma-1234#hash
```

Предлагаю сделать в модуле поддержку этого хэша. Например, при навигации с `Root`, мы находимся на панеле `panel1`, которая принадлежит вью `view1`. В данном случае хэш будет следующий:
```
#view1-panel1
```

Вызываем метод `go`:
```
navigator.go("panel2");
```
И хэш будет следующий:
```
#view1-panel2
```

При навигации с `Epic`:
```
#story1-panel2
```

Также, при запуске приложения с хэшем, было бы неплохо открывать нужную панель. Но так как перед этим могут загружаться важные данные или должно открыться что-то другое, то предлагаю сделать следующие методы.

`navigator.checkHash()` - возвращает `Boolean`, `true` - если хэш есть и он валидный, `false` - если хэша нет или он не валидный.
`navigator.followHash()` - переход на панель, указанную в хэше.

**Comment by YerinAlexey** [comment]
Не думаю, что это нужно встраивать в навигатор

**Comment by kosheeta** [comment]
> Не думаю, что это нужно встраивать в навигатор

Почему же? Эту функцию стоило бы добавить. Это очень удобно. Используя эту библиотеку, не так просто самому написать такую функциональность.

Ну, хотя-бы настройку хэша стоит добавить, чтобы он ставился при переходе.
