### ISSUE TITLE
Будущее проекта

### ISSUE THREAD

**Issue by YerinAlexey** [YerinAlexey/vkui-navigation#9]
Недавно я полностью переехал с Github на [Sourcehut](https://sr.ht) и все проекты перенёс туда. Вскоре я планирую перевести и vkui-navigation. Кто-то против?

@MrZillaGold?

**Comment by egorprnn** [comment]
Вообще окончательное решение таких вопросов остаётся за автором, но все же если это произойдёт, то будет немного печально из расчета базы пользователей Github и Sourcecut

**Comment by YerinAlexey** [comment]
> будет немного печально из расчета базы пользователей Github и Sourcecut

Вообще, в случае с Sourcehut, пользовательская база не имеет большого значения, так как там можно отправить патч или сообщить о проблеме просто написав письмо на нужный адрес.

**Comment by YerinAlexey** [comment]
Я решил, что проект остаётся на гитхабе, так будет меньше проблем с NPM
